---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  namespace: database
  annotations:
    external-dns.alpha.kubernetes.io/hostname: postgres.jennex.io
    io.cilium/lb-ipam-ips: 192.168.30.83
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres16
    role: primary
