apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:W1vyx6+x4AAxSr74ha1Rv8YDujiAPNgh63YmpH36IJ6TuUnkTbmxAZSBddJWJE9Jp8/6/NxTYVE7prPXcwINJtlW67DASh2N5DKYkIdFJzhNQkqyYcZhn1KPr1TpWw==,iv:7j8EZSJfIAZA5AHOMIXylTojskKpJ9rWAJVItfnxV7w=,tag:wMdFH3U/UdaUTxI5lBv+9Q==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:bk08/RuIFlzbqg==,iv:v3nCq549ja77+1i42pDcAYAWX2Zm6ndHtwLVr3MWHYY=,tag:tAyP38KlIbretDQFvsCQVA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:nmjMQwQkYAiSdSYxINiEp5w=,iv:bc8HylTFaJNWAJURNJ6YiP/RjvOQcEvSn3dRYB4zz8A=,tag:lUyPa9gsAU3q+gMr9jwp8A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:FwFbch188n4dQVKJjwHibThl6hRRObapNn+BQR1M+K75mm0V,iv:DVE6I6h/tVyOMCHxpzc/9HLCmiAYNdgPpGBwA2mfAlY=,tag:U6Exwwc3nWsc200AfB06Jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age149xz2rrv6ccfzlrgu2knf2y0q9cfq8rux4740lvc4xalegrawcjqg7glql
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bkhzZ05CV1FWaU54U1hH
            NjFuRjUxZWpEMkNySjNEajJuNFJrM0d4c1F3CnFoTzd5TzRIMjd0WU9lZjVZMjYv
            NEV4Wjd5VlB4dXlMRytEamkwWmE1eEkKLS0tIFJCL3BMeTBCQWVHeC84M0JnWFR2
            VVVUb2orS1pBK01vTVROV1lmVk1vdjAKQ7EN+EWqdYaAq83Y68fcAB2beoCjHO6j
            o+hNLAFNq2fnTH0+9AINvZSBekUk6L5B2+IxyqoMSEDsTK+p2xmTSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-24T07:46:21Z"
    mac: ENC[AES256_GCM,data:4MVFlcq+KNco+0QO54TIZKYVXR1+5AhwxEmATv1HMmoYwM3aqSfdvdIAYQbBpwH87WhpGcQuiTOs8TxOljlPGLm5ytdVJxMItakIIZnU9TxwPUMNCgDwZVZu5GIyuJ1Fe0Q3V7ly48qV80awQXpWAWy1ZkjuYRSc6TscH8cpCQ0=,iv:BaonYsS2ug8bWzaUQN/dwWQtSCHkAPNbhxThs67nb14=,tag:Kmd+82x21G05119NttS/gg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
