---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-config
  namespace: databse
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client-pvc
  resources:
    requests:
      storage: 15Gi
