apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:of2kpuoBt9HMYiFBhxw3AEdw9vFQASza9naNWACf+sk=,iv:4NLGQ4IGqjSx1Fo6OS5n/7dHzeGYWNDNmDvGnR47858=,tag:QDHX7iFnaFKFDQWmLm/oVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age149xz2rrv6ccfzlrgu2knf2y0q9cfq8rux4740lvc4xalegrawcjqg7glql
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1M3FxNkwwUHVkSU1LU3hQ
            UXo4dTl2SnRka0RWZE5pSTBXb1RSZ29nL3pFCmtXTGlaT1VOTmJRNGYxUjh3V2Mr
            NDNoa09jeE4rbTFtNHVza1lrdU1uWVEKLS0tIFFxRk5XSDlONjc0M3B4eXJ1RVE0
            aEhRMHQ3WHRxS1lBZWRyN2lOTzBIQWMKsvRIVM+UtzUBi6W/K3EXFPVqwxBTbObd
            Hzj5PTorba5QpA5YZh/1DuvPIEP77IIQf1FDT4pP4b2QGNywgsdvjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-24T07:46:21Z"
    mac: ENC[AES256_GCM,data:KYlMsiJViqwhSvUw/3td5hhvoYUGVCUYpJrRAmACrtZTE6Oy+pZk1/Vis8HE8dcsu+Q92En7qhFuBiQNebFXoN9M8HsYPjnBFVuYACy8Nz32WpLlD7Rk0IHCYuOZ2wn0MX8t6gTjWfEyRyK6iuHAXxPNBws7UiHp/esG7aWGCIA=,iv:7I6ClhayVQUrPhheUNBSc8+Q029od8T7Cn/UMlNHVBU=,tag:1Es9IC3oHjnWOztqHHq/oQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
