apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:sOyZIKp1ByMA9Uz0xzRxJWAJ3Afa2gMikV+ebDnireksMlKTujDIpA==,iv:/DjByCUrIUtSD2YVJpZO2gjKiWKQRaJ2veEzkG1RWNE=,tag:rAXCJZeNDKH9Ct9aRj+mFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age149xz2rrv6ccfzlrgu2knf2y0q9cfq8rux4740lvc4xalegrawcjqg7glql
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHOWdFVnFRRXovc1lHL2NQ
            b0JrRWxjSzVjOGw4T0JwTEhJWklIQzNKdDN3CmFpRTRMc043NWZjc09lQlJpZmtr
            bzQyRlY4bDZnNGJreHFWWW45RGlGSmMKLS0tIHQvTXRTenVxYWlCR3oxV0lwSDNo
            cnRDSkhabk1tYkZkc0VZb2l5M1NrOHMKcW9qTXunaypklNkN2z3PfgvM2/+rcGWB
            GLz6Ug1k9IbGsOMdGLSFORQHNr6kSE79rlDl6vjNGz+9UVevekjSXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-24T08:14:13Z"
    mac: ENC[AES256_GCM,data:jKsl/zFJYCDrXResfJpoFYLizfCqou9M+7S2iHYLV7BaecHd/o8/UHM6VmaYzQjReC7dSIyn+9ZrvIAOUm7p+Wf6ecRGDTbkcwHY9TChk2gIAqnTeeuwvjXUjHs/adM9VJgnfHirKub4Xl7U5Giq77d7YkRYGd993SeEXocO7vY=,iv:UlXlRtpJmNOPyHsFp0JfY5tsQe9gsgqWrMCSNrXihd8=,tag:eKuoB3p6u/MZZEgOjxoa7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
