---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mealie
  namespace: selfhosted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          enableServiceLinks: false

        containers:
          main:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v1.2.0
            env:
              ALLOW_SIGNUP: "false"
              PUID: 1000
              PGID: 1000
              BASE_URL: https://mealie.jennex.dev
              # LDAP_AUTH_ENABLED: "true"
              # LDAP_SERVER_URL: ldap://ak-outpost-ldap-outpost.security.svc.cluster.local
              # LDAP_BASE_DN: "dc=ldap,dc=bjw-s,dc=dev"
              # LDAP_QUERY_BIND:
              #   valueFrom:
              #     secretKeyRef:
              #       name: mealie-secret
              #       key: LDAP_QUERY_BIND
              # LDAP_QUERY_PASSWORD:
              #   valueFrom:
              #     secretKeyRef:
              #       name: mealie-secret
              #       key: LDAP_QUERY_PASSWORD
              # LDAP_USER_FILTER: "(memberOf=cn=bjw-s Members,ou=groups,dc=ldap,dc=bjw-s,dc=dev)"
              # LDAP_ADMIN_FILTER: "(memberOf=cn=bjw-s Admins,ou=groups,dc=ldap,dc=bjw-s,dc=dev)"
              # LDAP_ID_ATTRIBUTE: cn
              # LDAP_NAME_ATTRIBUTE: name
              # LDAP_MAIL_ATTRIBUTE: mail
              DB_ENGINE: sqlite
            resources:
              requests:
                cpu: 5m
                memory: 256Mi
              limits:
                memory: 512Mi

    service:
      main:
        ports:
          http:
            port: 9000

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
      internal:
        enabled: true
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}-internal.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        existingClaim: mealie-data
        globalMounts:
          - path: /app/data
